/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'aruba' at '20-2-27 上午1:27' with Gradle 2.14.1
 *
 * @author aruba, @date 20-2-27 上午1:27
 */
public class Library {
	public static void main(String arg[]){
		Library lib = new Library();
		if (lib.someLibraryMethod())
			System.out.println("When there is a fire, commit and push.");
    }
	
    public boolean someLibraryMethod() {
        return true;
    }
}
